# Stub skill for selectivity testing
id: stub_ci_pipeline
name: ci_cd
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["set up ci", "create pipeline"]
  soft:
    keywords: [ci, cd, pipeline, github actions, workflow, build, deploy, artifacts]

renderings:
  minimal:
    tokens: 50
    content: "CI/CD: fast feedback, cache deps, fail early, deploy on green."
  compact:
    tokens: 100
    content: "## CI/CD Pipeline\nRun tests first. Cache node_modules. Deploy only on main."
