# Stub skill for selectivity testing
id: stub_database_sql
name: sql_queries
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["write sql query", "database schema"]
  soft:
    keywords: [sql, query, database, postgres, mysql, migration, index, join]

renderings:
  minimal:
    tokens: 50
    content: "SQL patterns: indexed queries, avoid N+1, use transactions."
  compact:
    tokens: 100
    content: "## SQL Queries\nIndex frequently filtered columns. Batch inserts. Use EXPLAIN."
