# Stub skill for selectivity testing
id: stub_deploy_docker
name: docker_deployment
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["deploy with docker", "containerize this"]
  soft:
    keywords: [docker, container, dockerfile, compose, kubernetes, k8s, pod]

renderings:
  minimal:
    tokens: 50
    content: "Docker deployment: multi-stage builds, layer caching, health checks."
  compact:
    tokens: 100
    content: "## Docker Deployment\nMulti-stage builds. Minimize layers. Use .dockerignore."
