# Stub skill for selectivity testing
id: stub_docs_readme
name: documentation
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["write documentation", "update readme"]
  soft:
    keywords: [docs, documentation, readme, markdown, jsdoc, docstring, wiki]

renderings:
  minimal:
    tokens: 50
    content: "Documentation: clear examples, API reference, quickstart guide."
  compact:
    tokens: 100
    content: "## Documentation\nStart with quickstart. Include code examples. Keep updated."
