# Stub skill for selectivity testing
id: stub_refactor_patterns
name: refactoring
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["refactor this", "clean up code"]
  soft:
    keywords: [refactor, cleanup, extract, rename, simplify, dry, solid]

renderings:
  minimal:
    tokens: 50
    content: "Refactoring: small steps, keep tests green, extract then inline."
  compact:
    tokens: 100
    content: "## Refactoring\nTests first. Small commits. Extract method, then decide."
