# Stub skill for selectivity testing
id: stub_testing_unit
name: unit_testing
version: "0.1.0"
scope: core
tier: untested

triggers:
  hard:
    intents: ["write unit tests", "test this function"]
  soft:
    keywords: [test, unittest, pytest, jest, mock, assert, coverage]

renderings:
  minimal:
    tokens: 50
    content: "Unit testing patterns: arrange-act-assert, isolation, mocking dependencies."
  compact:
    tokens: 100
    content: "## Unit Testing\nArrange-Act-Assert pattern. Mock external deps. Test edge cases."
