# Skill Schema v1.1 - Mobile Accessibility
id: skill_design_a11y
name: accessibility_mobile
version: "1.0.0"
scope: core
tier: core

classification:
  type: prompt
  domain: [design, accessibility, mobile, a11y]
  primary_action: design_accessible

description:
  short: "Design accessible mobile interfaces (WCAG compliance)"
  full: |
    Accessibility patterns for mobile: contrast, touch targets, screen readers,
    motion sensitivity, and inclusive design principles.

triggers:
  hard:
    intents:
      - "make it accessible"
      - "accessibility check"
      - "wcag compliance"
  soft:
    keywords:
      - accessible
      - accessibility
      - a11y
      - wcag
      - contrast
      - screen reader
      - voiceover
      - talkback
    embedding_threshold: 0.7
  budget:
    priority: 7
    min_tokens: 80
    max_tokens: 450

renderings:
  minimal:
    tokens: 70
    content: |
      **Accessibility**: Touch targets 44px+, contrast 4.5:1 (text) 3:1 (large), labels for all inputs, color+icon for status, reduce motion option, semantic HTML/roles.

  compact:
    tokens: 200
    content: |
      ## Mobile Accessibility

      **Touch Targets**
      - Minimum: 44x44px
      - Spacing between: 8px
      - Easy to distinguish active areas

      **Color & Contrast**
      - Text contrast: 4.5:1 minimum (WCAG AA)
      - Large text: 3:1 minimum
      - UI components: 3:1
      - Never use color alone for meaning

      **Screen Readers**
      - All images need alt text
      - Form inputs need labels
      - Buttons describe action
      - Logical reading order

      **Motion & Animation**
      - Respect prefers-reduced-motion
      - No flashing >3 times/second
      - Allow pause/stop for animations

      **Forms**
      - Visible focus states
      - Error messages linked to inputs
      - Clear validation feedback
      - Large enough input fields (48px)

      **Testing**
      - Enable VoiceOver/TalkBack and navigate
      - Zoom to 200% and check layout
      - Test with one hand

  full:
    tokens: 400
    content: |
      ## Mobile Accessibility (v1.0.0)

      ### Touch Target Guidelines
      - **Minimum size**: 44x44px (48px preferred)
      - **Spacing**: 8px between adjacent targets
      - **Visual feedback**: Clear pressed states
      - **Hit areas**: Can be larger than visual element

      ### Color & Contrast (WCAG AA)
      | Element | Minimum Ratio |
      |---------|---------------|
      | Normal text (<18px) | 4.5:1 |
      | Large text (>=18px) | 3:1 |
      | UI components | 3:1 |
      | Focus indicators | 3:1 |

      **Color Independence**
      - Always pair color with icon/text
      - Error: red + error icon + message
      - Success: green + checkmark + message
      - Links: color + underline

      ### Screen Reader Support

      **Images**
      - Decorative: `aria-hidden="true"`
      - Informative: descriptive alt text
      - Complex: detailed description

      **Interactive Elements**
      - Buttons: describe action ("Submit form")
      - Links: describe destination
      - Custom controls: proper ARIA roles

      **Reading Order**
      - Visual order = DOM order
      - Logical heading hierarchy (h1 > h2 > h3)
      - Group related content

      ### Motion & Animation
      ```css
      @media (prefers-reduced-motion: reduce) {
        * { animation: none !important; transition: none !important; }
      }
      ```
      - No content that flashes >3/second
      - Auto-playing media must be pausable
      - Carousels need manual controls

      ### Form Accessibility
      - Labels above or beside inputs (not placeholder-only)
      - Error messages: associate with input via aria-describedby
      - Required fields: marked visually and programmatically
      - Focus order: logical tab sequence

      ### Testing Checklist
      1. [ ] Enable VoiceOver/TalkBack, navigate entire flow
      2. [ ] Zoom to 200%, verify no content loss
      3. [ ] Check all color contrast ratios
      4. [ ] Test with one hand (thumb reachability)
      5. [ ] Verify focus indicators are visible
      6. [ ] Test with reduced motion enabled

lifecycle:
  created_at: "2026-02-15T12:00:00Z"
  provenance: ["decision_20260215_cms_design_pack"]
