# Skill Schema v1.1 - Design Critique
id: skill_design_critique
name: design_critique
version: "1.0.0"
scope: core
tier: core

classification:
  type: prompt
  domain: [design, review, critique, evaluation]
  primary_action: critique_design

description:
  short: "Evaluate designs against quality criteria and best practices"
  full: |
    Structured design critique framework: visual hierarchy, usability,
    consistency, accessibility, and emotional impact evaluation.

triggers:
  hard:
    intents:
      - "review this design"
      - "critique this"
      - "evaluate the design"
      - "what's wrong with this"
  soft:
    keywords:
      - critique
      - review
      - evaluate
      - feedback
      - improve
      - better
      - issues
      - problems
    embedding_threshold: 0.7
  budget:
    priority: 7
    min_tokens: 100
    max_tokens: 500

renderings:
  minimal:
    tokens: 80
    content: |
      **Design Critique**: Evaluate on 8 axes: Hierarchy, Balance, Contrast, Consistency, Whitespace, Alignment, Typography, Color. Rate 1-5, identify top 3 issues, suggest specific fixes.

  compact:
    tokens: 220
    content: |
      ## Design Critique Framework

      **8-Point Evaluation**
      1. **Hierarchy**: Is importance clear? Eyes go where intended?
      2. **Balance**: Visual weight distributed well?
      3. **Contrast**: Key elements stand out? Text readable?
      4. **Consistency**: Same patterns used throughout?
      5. **Whitespace**: Enough breathing room? Not cramped?
      6. **Alignment**: Elements on grid? Nothing floating?
      7. **Typography**: Readable? Appropriate scale?
      8. **Color**: Palette cohesive? Semantic usage correct?

      **Critique Process**
      1. First impression (3 seconds): what grabs attention?
      2. Scan for issues: misalignments, contrast, clutter
      3. Rate each axis 1-5
      4. Identify top 3 problems
      5. Provide specific, actionable fixes

      **Feedback Format**
      - "The [element] creates [problem] because [reason]. Fix by [action]."
      - Example: "The CTA button is lost because it uses the same weight as body text. Fix by increasing size to 18px and using primary color."

  full:
    tokens: 450
    content: |
      ## Design Critique Framework (v1.0.0)

      ### Evaluation Criteria (Rate 1-5)

      **1. Visual Hierarchy**
      - Primary element immediately obvious?
      - Eye flow follows intended path?
      - F-pattern or Z-pattern respected?

      **2. Balance & Composition**
      - Visual weight evenly distributed?
      - Symmetry or intentional asymmetry?
      - No section feels heavier than others?

      **3. Contrast**
      - Key actions stand out?
      - Text meets WCAG AA contrast?
      - Visual separation between sections?

      **4. Consistency**
      - Same spacing values used?
      - Consistent button styles?
      - Matching iconography?

      **5. Whitespace**
      - Content has room to breathe?
      - Not overcrowded?
      - Margins and padding consistent?

      **6. Alignment**
      - Elements snap to grid?
      - No "floating" components?
      - Consistent left/center/right alignment?

      **7. Typography**
      - Hierarchy clear (size/weight)?
      - Line length readable?
      - Font pairing harmonious?

      **8. Color Usage**
      - Palette cohesive?
      - Semantic colors correct?
      - Not overusing accent colors?

      ### Critique Process
      1. **3-Second Test**: What do you notice first?
      2. **Squint Test**: Does hierarchy hold when blurred?
      3. **Systematic Scan**: Check each criterion
      4. **Identify Top 3**: Most impactful issues
      5. **Specific Fixes**: Actionable recommendations

      ### Feedback Structure
      ```
      Issue: [What's wrong]
      Impact: [Why it matters]
      Fix: [Specific action to take]
      ```

      Example:
      ```
      Issue: CTA button blends with card background
      Impact: Users might miss the primary action
      Fix: Change button fill to primary color (#8B5CF6), increase padding to py-3 px-6
      ```

lifecycle:
  created_at: "2026-02-15T12:00:00Z"
  provenance: ["decision_20260215_cms_design_pack"]
