# Skill Schema v1.1 - Layout Principles
id: skill_design_layout
name: layout_principles
version: "1.0.0"
scope: core
tier: core

classification:
  type: prompt
  domain: [design, layout, ui, structure]
  primary_action: design_layout

description:
  short: "Apply layout principles for visual hierarchy and structure"
  full: |
    Core layout principles for UI design: visual hierarchy, grid systems,
    spacing rhythm, alignment, and responsive breakpoints.

triggers:
  hard:
    intents:
      - "design layout"
      - "create screen"
      - "structure page"
      - "layout this"
  soft:
    keywords:
      - layout
      - grid
      - structure
      - hierarchy
      - spacing
      - align
      - page
      - screen
      - dashboard
    embedding_threshold: 0.7
  budget:
    priority: 9
    min_tokens: 100
    max_tokens: 600

constraints:
  requires: []
  forbids: []
  timeout_seconds: 30

renderings:
  minimal:
    tokens: 80
    content: |
      **Layout Principles**: Use visual hierarchy (size/weight/color), consistent spacing rhythm (8px base), align to grid, group related items, use whitespace to separate sections.

  compact:
    tokens: 250
    content: |
      ## Layout Principles

      **Visual Hierarchy**
      - Size: larger = more important
      - Weight: bolder = more attention
      - Color: primary/accent for key actions
      - Position: top-left reads first (F-pattern)

      **Spacing System** (8px base)
      - Tight: 4-8px (related items)
      - Normal: 12-16px (component gaps)
      - Loose: 24-32px (section breaks)
      - Page padding: 16-24px mobile, 32-48px desktop

      **Alignment**
      - Left-align text blocks
      - Center-align CTAs and headers sparingly
      - Use consistent grid columns (4/8/12)

      **Grouping**
      - Related items should be visually connected
      - Use cards, borders, or backgrounds to group
      - Whitespace separates unrelated sections

  full:
    tokens: 500
    content: |
      ## Layout Principles (v1.0.0)

      ### Visual Hierarchy
      Guide the eye through intentional contrast:
      1. **Size**: Larger elements draw attention first
      2. **Weight**: Bold text creates emphasis
      3. **Color**: Primary/accent colors highlight key actions
      4. **Position**: Top-left is read first (F-pattern), center for focus

      ### Spacing System
      Use an 8px base unit for consistent rhythm:
      - **4px**: Icon padding, inline spacing
      - **8px**: Related item gaps
      - **12-16px**: Component internal padding
      - **24px**: Card gaps, section internal spacing
      - **32-48px**: Major section breaks
      - **Page padding**: 16-24px (mobile), 32-64px (desktop)

      ### Grid System
      - Mobile: 4 columns, 16px gutter
      - Tablet: 8 columns, 24px gutter
      - Desktop: 12 columns, 32px gutter
      - Max content width: 1200-1440px

      ### Alignment Principles
      - Left-align body text (easier to read)
      - Center-align headings sparingly
      - Right-align numeric data in tables
      - Consistent baseline alignment

      ### Grouping & Proximity
      - Items that belong together should be visually connected
      - Use cards, subtle backgrounds, or borders
      - Whitespace is a powerful separator
      - Group by function, not just appearance

      ### Common Patterns
      - **Header**: Logo left, nav center/right, action button right
      - **Content**: Main content left (2/3), sidebar right (1/3)
      - **Cards**: Equal-width grid, consistent heights per row
      - **Forms**: Single column, labels above inputs

lifecycle:
  created_at: "2026-02-15T12:00:00Z"
  provenance: ["decision_20260215_cms_design_pack"]
