# Skill Schema v1.1 - Mobile Spacing System
id: skill_design_mobile_spacing
name: mobile_spacing
version: "1.0.0"
scope: core
tier: core

classification:
  type: prompt
  domain: [design, mobile, spacing, ui]
  primary_action: design_mobile

description:
  short: "Mobile-first spacing and touch-friendly design patterns"
  full: |
    Mobile-specific spacing, touch targets, safe areas, and responsive
    patterns for mobile-first UI design.

triggers:
  hard:
    intents:
      - "design for mobile"
      - "mobile spacing"
      - "touch targets"
  soft:
    keywords:
      - mobile
      - touch
      - spacing
      - responsive
      - phone
      - ios
      - android
      - safe area
      - bottom sheet
    embedding_threshold: 0.7
  budget:
    priority: 8
    min_tokens: 80
    max_tokens: 500

renderings:
  minimal:
    tokens: 70
    content: |
      **Mobile Spacing**: Touch targets min 44x44px. Page padding 16-20px. Bottom nav height 56-64px. Safe area insets for notch. Content max-width 402px for phone viewport.

  compact:
    tokens: 200
    content: |
      ## Mobile Spacing System

      **Touch Targets**
      - Minimum: 44x44px (Apple HIG)
      - Comfortable: 48x48px
      - Spacing between targets: 8px minimum

      **Page Layout**
      - Horizontal padding: 16-20px (px-4 to px-5)
      - Header top padding: 48-60px (accounts for status bar)
      - Bottom padding: 80-100px (accounts for nav bar)
      - Content max-width: 390-430px (standard phone)

      **Component Spacing**
      - Card padding: 16px (p-4)
      - List item height: 48-56px
      - List item padding: px-4 py-3
      - Section gaps: 24-32px

      **Safe Areas**
      - Top: status bar (44-50px)
      - Bottom: home indicator (34px)
      - Notch: dynamic island (60px from top)

      **Bottom Navigation**
      - Height: 56-64px (plus safe area)
      - Icon size: 24px
      - Label size: 10-12px

  full:
    tokens: 450
    content: |
      ## Mobile Spacing System (v1.0.0)

      ### Touch Target Guidelines
      **Size Requirements**
      - Minimum: 44x44px (Apple HIG requirement)
      - Recommended: 48x48px (comfortable tapping)
      - Large buttons: 56px height
      - Spacing between targets: 8px minimum

      **Touch-Friendly Patterns**
      - Buttons: full-width on mobile
      - Links: pad with invisible touch area
      - Close buttons: place in corners (easy reach)
      - Primary actions: bottom of screen (thumb zone)

      ### Page Layout
      **Horizontal Spacing**
      - Edge padding: 16px (compact) to 20px (comfortable)
      - Card margins: 16px from edges
      - Full-bleed images: 0px padding

      **Vertical Spacing**
      - Status bar clearance: 44-60px top padding
      - Page header: pt-6 (24px) below status
      - Section gaps: 24-40px
      - Bottom clearance: 80-100px (nav + safe area)

      **Content Dimensions**
      - Max width: 390-430px (standard phone viewport)
      - Optimal reading width: 320-380px
      - Hero image: full width, 200-300px height

      ### Safe Areas (iOS/Android)
      | Area | iPhone Standard | iPhone Notch | Android |
      |------|-----------------|--------------|---------|
      | Top | 20px | 44-60px | 24px |
      | Bottom | 0px | 34px | 0-48px |

      ### Component Standards
      **Navigation**
      - Bottom nav height: 56px + safe area
      - Tab bar icons: 24x24px
      - Active indicator: 3px underline or filled

      **Lists**
      - Row height: 48-72px
      - Swipe actions: 80px revealed width
      - Dividers: 1px, inset 16px from left

      **Cards**
      - Padding: 16px all sides
      - Border radius: 12-16px
      - Shadow: subtle (0 2px 8px rgba)
      - Gap between cards: 12-16px

      ### Thumb Zone
      - Primary actions: bottom 1/3 of screen
      - Secondary actions: middle
      - Rarely-used: top (harder to reach)

lifecycle:
  created_at: "2026-02-15T12:00:00Z"
  provenance: ["decision_20260215_cms_design_pack"]
